### PR TITLE
feat: add optional ServiceAccount resource

### PR DESCRIPTION
**Pull request by MattMencel**

### CODE REVIEW

**Comment by MattMencel** [comment]
Alternatively... if the `serviceAccountName` in the Deployment is configurable with a value, the ServiceAccount could be provisioned separately from this helm chart.

**Review by wrenhunter — APPROVED** [review]
Hi Matt, this looks good, thanks for the contribution!

**Comment by MattMencel** [comment]
@wrenhunter Thanks!

I did forget to update the README. Is there another process to update the helm repo with the updated chart?

**Comment by MattMencel** [comment]
@wrenhunter I don't see the new chart yet in the Helm Repo. So just wondered when it would be published.

``` sh
helm search repo strongdm                                                                                                                                                                                                             
NAME               	CHART VERSION	APP VERSION	DESCRIPTION
strongdm/sdm-client	0.1.0        	1.0.0      	strongDM Client Container
strongdm/sdm-relay 	0.1.1        	1.0.0      	strongDM Relay
```

**Comment by wrenhunter** [comment]
@MattMencel I see what you mean. I'll need to track down a colleague with access to Artifact, so that we can push the changes. I'll let you know when that happens, probably next week.

**Comment by wrenhunter** [comment]
Hi @MattMencel, the Artifact repo is updated. We're seeing an issue with the repo icons there, but no effect on your update, we'll get that sorted this week.

**Pull request merged**
